getappmap/vscode-appland

media/scenario.js
The 'show' even is fired before the tab is fully visible. By listening for the 'shown' event, the lines are able to be positioned properly.
Fixes #2
=> Fix invisible connection lines in flow view

package-lock.json, package.json, rollup.config.js
It causes rollup to produce empty sourcemaps for me. I've spent hours trying to find this problem and then to debug it; in the end
I decided it's not worth the trouble. The extension is still in development, the source code is small and public. We can revisit when needed.
=> Remove rollup-plugin-terser

media/scenario.js, src/scenarioViewer.ts
The extension code tried to send an 'update' message to the webview
as soon as it finished setting it up; however, the webview might
not have set its message handler by then. Instead let the webview
tell the extension when it's ready to avoid the race.
=> Avoid a race when first showing code

README.md
- updated the VSCode Marketplace AppMap link
- added python section in the installation steps
- the "Onboarding to code" video thumbail no longer restricted to 300px width
=> docs: adding documentation for python

doc/TUTORIAL-PYTHON-CHIPYORG.md
This a small update of the python step-by-step tutorial. 
Fixing a typo and replacing two screenshots with an animated gif showing chipy.org appmaps.
=> docs: typo and animated gif

README.md
Updates of README.md:
- moved the link to Discord above the first gif
- softened dependency on tests
- added a link to a Py tutorial
- added links to remote recording instructions for appmap clients
- moved "contact us" to the top of the troubleshooting section
=> docs: softened dependency on tests, small edits

README.md
Added a loom video and a link to Java tutorial to README.md.
=> fix: adding java video and tutorial to docs

doc/TUTORIAL-PYTHON-CHIPYORG.md
Minor tutorial update - adding video, removing shell prompt signs from instructions
=> docs: adding video to chipy tutorial

README.md
Adds social links to the Extension readme/marketplace
- Dev.to blog
- Twitter for AppMap Ruby, Python & Java accounts
=> feat: add social links to extension

.travis.yml, DEVELOPMENT.md, package.json, src/extension.ts, src/registerUtilityCommands.ts, src/remoteRecording.ts, src/scenarioViewer.ts, src/tree/linkTreeDataProvider.ts, src/util.ts, test/runTest.ts
This update adds a new command "AppMap: Reset usage state" that erases global and workspace states that remember AppMap usage by the user.
Changes:
- `src/util.js`
- new function `registerUtilityCommands()` that registers the new `appmap.resetUsageState()` command
- the new command resets all workspace and global states stored by the extension
-  new `get/setQuickstartSeen` which stores state of the quickstart seen by the user
- `src/extension.ts`
- calls the new functions in `utils.js`
- `src/remoteRecording.ts, scenarioViewer.rs, linkTreeDataProvider.ts`
- added `resetState()` to all classes that modify the global or workspace states. This function cleans each class's own mess. Called by `appmap.resetUsageState()` in `src/utils.js`
- `package.json`
- new command `appmap.resetUsageState` …
=> feat: Reset saved usage state

src/tree/links.ts
A trivial update - `src/tree/links.ts` was updated with real links to AppMap documentation.
=> fix: Side view milestones have real links to docs

src/extension.ts, src/tree/index.ts
Prevent the `Open AppMaps` quickstart view from opening upon extension initialization
Resolves #315
=> fix: Don't open a webview upon initialization

.eslintrc.json, package.json, src/agent/AppMapAgentDummy.ts, src/appmapUploader.ts, src/projectWatcher.ts, src/registerUtilityCommands.ts, src/scenarioViewer.ts, src/tree/index.ts, src/tree/milestoneTreeDataProvider.ts, types/@appland/index.d.ts, types/custom.d.ts, web/src/appmapView.js, webpack/extension.config.js, webpack/webview.config.js, yarn.lock
**First version of AppMap Uploader**
For test purpose, I had to change `appmap` dependency to be loaded from a local file, as there's no released version yet.
When running `npm install`, remove `node_modules/@appland/appmap` if you encounter installation errors, as it apparently cannot be replaced by a symlink automatically.
After uploading, it displays a notification and opens a browser window, where the uploaded data is collected and added to the user profile. For that to work, you have to use `feature/vscode-upload-handling` branch for AppLand from `Appmap-server` PR#863(https://github.com/applandinc/appmap-server/pull/863) and change `appMap.appLandURL` configuration value to point to your local instance.
=> feat: upload AppMap to AppLand server

src/scenarioViewer.ts, src/telemetry/telemetryResolver.ts, src/util.ts
This caused an issue when constructing telemetry data where a numeric value was coerced into a string.
=> fix: Don't coerce arbitrary types into strings

src/extension.ts, src/scenarioViewer.ts
This functionality was added in #169 , but later it was removed because there was a bug with not working `setState` command when few Appmaps were opened.
=> fix: get/set Appmap state

DEVELOPMENT.md, src/analyzers/index.ts, src/analyzers/java.ts, src/analyzers/python.ts, src/analyzers/ruby.ts, src/analyzers/unknown.ts, src/languageResolver.ts
- Use LanguageResolver to detect languages.
- Don't pretend a project is some supported language if there's just
a single script in it among other more common language.
=> fix: More robust language detection in project overview

src/telemetry/properties/versionControlGit.ts
The previous behavior would cause a .gitignore containing `*` at a non-root level to ignore everything in the project.
Instead, given the path `./child/.gitignore`, a filter of `*` would be applied as `./child/*` as intended.
Resolves MAP-297
=> fix: Non-root level gitignores will no longer be treated as root

package.json, src/analyzers/index.ts, src/configuration/extensionSettings.ts, src/configuration/extensionState.ts, src/extension.ts, src/services/appmapCollection.ts, src/services/projectStateService.ts, src/tree/instructionsTreeDataProvider.ts, src/webviews/installGuideWebview.ts, src/webviews/openAppmapsWebview.ts, src/webviews/projectPickerWebview.ts, src/workspace/projectMetadata.ts, web/src/installGuideView.js, web/src/openAppMapsView.js, yarn.lock
This change:
- Adds the `Open AppMaps` page back into the instructions list
- Allows listeners to bind to workspace flag updates via `ExtensionState`
- Once published, integrates the changes from https://github.com/applandinc/appmap-js/pull/604
=> feat: Add `Open AppMaps` to updated instructions

src/commands/outOfDateTests.ts, src/extension.ts, src/hover/appmapHoverProvider.ts, src/lib/bestFilePath.ts, src/lib/touch.ts, src/lib/workspaceFolderForDocument.ts, src/terminalLink/appmapLinkProvider.ts, src/textEditor/appmapTextEditorProvider.ts, src/util.ts, test/integration/codeObjects/index.test.ts, test/integration/index/updateAsAppMapsAreModified.test.ts, test/integration/terminalLink/terminalLink.test.ts, test/integration/uptodate/outOfDate.test.ts, test/integration/uptodate/uptodate.test.ts, test/integration/util.ts
Scan the VSCode terminal for `*.appmap.json`. Handle Command-Click by opening the corresponding AppMap, including the line number, if available.
=> feat: Terminal link provider

src/services/languageResolver.ts
Removed the check for `agent.enabled` because it returned `UNKNOWN_LANGUAGE` results for Python instead of the results generated from the analyzer in `python.disabled.ts`.
=> fix: allow analyzer results for python to be returned

src/diagnostics/findingsDiagnosticsProvider.ts, src/lib/generateDisplayTitle.ts, src/tree/findingsTreeDataProvider.ts
[Issue 64](https://github.com/applandinc/board/issues/64)
This PR changes the way items are listed in the Findings menu in VSCode.
New Pattern: `[Rule] in [context], [file:line]`
=> fix: Create getTreeName function to format tree name

src/analyzers/index.ts, src/services/command.ts, src/services/projectStateService.ts, src/workspace/projectMetadata.ts
Fixes https://github.com/applandinc/board/issues/88
This adds a boolean to the project metadata that signifies if a supported node version was detected. This gets propagated to the frontend so that we can conditionally render a message helping users install the correct version of node.
=> Fix: send node status to frontend

src/configuration/extensionState.ts, src/services/runtimeAnalysisCtaService.ts
Avoid putting the CTA in front of all users - just new users.
I think this is actually the way we want it to work - right?
=> feat: CTA is conditional on extension version

.travis.yml, package.json, src/commands/deleteAllAppMaps.ts, src/services/projectStateService.ts, test/integration/editor/opensBySourcePathAndState.test.ts, test/integration/util.ts, test/integrationTest.ts, test/system/tests/instructions.test.ts
A few changes to make the extension test run more reliably. My final test run saw `yarn test:extension` complete 50 consecutive runs without any failures.
Fixes #443 .
=> Make the extension test more reliable

.vscode/launch.json, package.json, src/editor/appmapEditorProvider.ts, test/system/src/driver.ts, test/system/src/instructionsWebview.ts, test/systemTest.ts, yarn.lock
One annoying aspect of the editor is that when switching tabs the current context is lost. This fixes this problem.
=> feat: Keep viewer state when switching tabs

.gitattributes, package.json, src/services/nodeDependencyProcess.ts, src/tree/index.ts, src/tree/instructionsTreeDataProvider.ts, src/util.ts, src/webviews/installGuideWebview.ts, test/fixtures/workspaces/project-early-access-eligible/.vscode/settings.json, test/integration/util.ts, test/integrationTest.ts, test/system/src/app.ts, yarn.lock
- The button shown didn't actually work since recent changes removed instructions feature flag.
- After fixing that, the button always led to 'install agent' page, even when it was already installed. Now it opens first not done instruction page.
Fixes https://github.com/applandinc/board/issues/87
=> Improve the button shown in the appmaps list when no appmaps have been detected

.vscode/launch.json, src/appMapService.ts, src/extension.ts, src/services/appmapCollectionFile.ts, src/services/appmapLoader.ts, src/tree/appMapTreeDataProvider.ts, src/tree/index.ts, test/integration/appmaps/appmapsTree.test.ts, test/integration/extension.test.ts, test/system/src/appMap.ts
AppMaps are organized according to the way they are recorded:
"Requests" are sorted by timestamp, other groups are sorted alphabetically. Maybe they should all be sorted by timestamp? But it makes AppMaps of test cases hard to find. I guess it should be configurable.
Full functionality is dependent on the agent conforming to AppMap 1.9.0 - https://github.com/applandinc/appmap/pull/32
=> feat: Categorize AppMaps

src/extension.ts, src/telemetry/definitions/events.ts, src/telemetry/index.ts, src/telemetry/sendAppMapCreateEvent.ts
This event is only sent for the first AppMap seen in a session. It will help us make sure our users are successful in making use of the extension and AppMap agents.
Fixes #458
=> feat: Send a telemetry event for AppMap creation

src/services/appmapUptodateService.ts
I noticed that `uptodate` processing isn't working. The test case has been passing because only a test is out of date. But when the output contains multiple lines, it isn't being processed correctly.
=> fix: Fix multi-line processing of uptodate output

package.json, src/commands/installAgent.ts, src/extension.ts, src/services/nodeProcessService.ts, src/telemetry/definitions/events.ts, src/util.ts, src/webviews/installGuideWebview.ts, test/integration/command/installAgent.test.ts, test/integration/editor/opensBySourcePathAndState.test.ts, test/integration/util.ts, test/system/src/instructionsWebview.ts, test/system/tests/instructions.test.ts, web/src/installGuideView.js, yarn.lock
=> feat: add command to install appmap agent

package.json, src/analyzers/index.ts, src/analyzers/python.ts, src/configuration/extensionState.ts, src/services/findingsIndex.ts, src/services/nodeProcessServiceInstance.ts, src/services/projectStateService.ts, src/tree/instructionsTreeDataProvider.ts, src/util.ts, src/webviews/installGuideWebview.ts, src/workspace/installationStatus.ts, src/workspace/projectMetadata.ts, test/fixtures/workspaces/project-system/appmap-findings.json, test/integration/findingsImpactDomains/noFindings.test.ts, test/integration/findingsImpactDomains/oneFinding.test.ts, test/integration/findingsImpactDomains/severalFindings.test.ts, test/integration/sampleCodeObjects/codeObjects.test.ts, yarn.lock
A ton of excess work was being performed on any minor update (new finding, new AppMap, state change).
I've broken the logic up so it'll only update relevant metadata depending on what changed, and project analysis will only occur once.
This PR also adds Pipenv support for Python projects. I originally added this in a separate PR but it ultimately ended up not working without the rest of the fixes in this PR.
=> fix: Don't fully analyze the project on every change update

src/extension.ts, src/services/appmapWatcher.ts, src/services/fileChangeEmitter.ts, src/telemetry/definitions/errorCodes.ts, src/telemetry/definitions/properties.ts
This PR contains some additional changes that I discovered while investigating #495 :
- Pre-existing AppMaps will not emit an `appmap:create` event upon initialization
- `appmap:create` will now be sent properly
- Errors which occur during initialization will receive an error code to reflect the failed initialization
Resolves #495
=> Emit `appmap:create`

src/telemetry/properties/versionControlGit.ts, test/integration/gitProperties.test.ts
I'm not sure how this is possible, but some user's report an error similar to:
```
RangeError: path should be a `path.relative()`d string, but got "/yarn.lock"
```
This occurs regardless of the OS, sometimes using Windows path separators (e.g. `\yarn.lock`).
These paths must have double separators? I'm not sure how it's occurring, but this should fix it.
=> fix: Strip paths of any extra leading path separators

src/analyzers/javascript.ts, test/integration/projectAnalyzers/javascript.test.ts
If a user specifies their mocha version as `latest`, we will fail when checking the version for compatibility because we're expecting a semver style version constraint. If it's `latest`, we'll always pass the check.
=> fix: Prevent semver comparison with 'latest'

src/telemetry/properties/versionControlGit.ts, test/integration/gitProperties.test.ts
The `ignore` library will raise an exception if it receives an empty string. This could happen when checking if the root of a project is ignored. Instead of allowing this to happen, we'll now always return false.
=> fix: Don't fail when checking if the project root is ignored

src/extension.ts, src/services/projectStateService.ts, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, test/integration/telemetry/properties.test.ts
`project:open` is now emit after the project has been analyzed, notifying on it's installable status and whether or not it contains a `devcontainer.json`/`.devcontainer.json`.
=> Notify whether a project is installable and contains a devcontainer 

src/actions/promptInstall.ts, src/configuration/extensionState.ts, src/extension.ts, src/services/workspaceServices.ts, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, src/webviews/installGuideWebview.ts, test/disabled/installGuide.test.ts, test/integration/actions/promptInstall.test.ts
Users who open a project which is supported by AppMap, but contains no `appmap.yml` will receive a notification prompting them to install.
This popup will not open for new users immediately after installation as we're already opening the instructions automatically. Maybe it's worth revisiting this?
Clicking `Open instructions` will open the instructions view to the project picker.
Clicking `Later` will simply close the notification. It will appear again the next time the project is opened.
Clicking `Don't show again` will silence the notification, but only for the currently opened project.
=> Prompt users to install if the project is supported

src/services/nodeProcessService.ts, test/integration/actions/promptInstall.test.ts, test/integration/nodeProcesses/backgroundProcess.test.ts, test/integration/util.ts
This is fully tested by automation.
- If `appmap_dir` is set within `appmap.yml` the processes will use it.
- If it's unset, `--appmap-dir .` will be used, effectively falling back to the project directory. 
These changes can be observed in the `Output` -> `AppMap: Services` log.
```
917952 [Stdout] spawned /opt/vscode/code --ms-enable-electron-run-as-node --ms-enable-electron-run-as-node /home/db/.config/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/cli.js index --watch --appmap-dir . with options {"retryTimes":3,"retryThreshold":180000,"id":"index","binPath":"/home/db/.config/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/cli.js","log":{"name":"AppMap: Services"},"args":["index","--watch","--appmap-dir","."],"cwd":"/home/db/dev/appla …
```
=> AppMap CLI and scanner specify `--appmap-dir` parameters

src/services/nodeProcessService.ts
The lock was being released before dependencies were installed. This may result in either:
- Another process installing simultaneously or
- Background services attempting to launch before they're ready
=> fix: Wait for `yarn up` before releasing installation lock

package.json, src/analyzers/index.ts, src/extension.ts, src/services/findingsIndex.ts, src/services/resolvedFinding.ts, src/tree/findingsTreeDataProvider.ts, src/webviews/findingInfoWebview.ts, src/webviews/findingsWebview.ts, src/webviews/installGuideWebview.ts, test/system/src/appMap.ts, test/system/src/driver.ts, test/system/src/findingDetailsWebview.ts, test/system/src/findingsOverviewWebview.ts, test/system/src/instructionsWebview.ts, test/system/tests/findings.test.ts, web/src/app.js, web/src/appmapView.js, web/src/findingsInfo.js, web/src/findingsView.js, web/src/installGuideView.js, yarn.lock
Fixes #520
This PR uses webviews that are available from [this PR](https://github.com/getappmap/appmap-js/pull/838)
This PR adds webviews to the VS Code extension that provide information about findings. There are three main changes:
1. The `Runtime Analysis` tree view is now organized:
2. There is a `Findings Overview` page:
3. There is a `Finding Details` page for each finding:
1. Build [this branch](https://github.com/getappmap/appmap-js/tree/analysis-findings) of `appmap-js` locally.
a. `git clone https://github.com/getappmap/appmap-js.git`.
b. `cd appmap-js`.
c. `git checkout analysis-findings`.
d. `yarn`.
e. `yarn build`.
5. Checkout this branch of `vscode-appland`.
6. Add this to the bottom of you `package.json` file in `vscode-appland`, replacing `YOUR_PATH` with the path to …
=> Update VS Code for Runtime Analysis Findings Pages

src/telemetry/definitions/properties.ts, src/util.ts, test/integration/telemetry/util.test.ts
Nested values are now returned, e.g.:
```
"appmap.file.metadata.app": "scanner/ruby-fixture",
"appmap.file.metadata.language.name": "ruby",
"appmap.file.metadata.language.engine": "ruby",
"appmap.file.metadata.language.version": "3.0.1",
"appmap.file.metadata.client.name": "appmap",
"appmap.file.metadata.client.url": "https://github.com/applandinc/appmap-ruby",
"appmap.file.metadata.client.version": "0.83.4",
"appmap.file.metadata.name": "Crypt crypt aes 256 gcm",
"appmap.file.metadata.source_location": "test/crypt_test.rb:11",
"appmap.file.metadata.frameworks.0.name": "minitest",
"appmap.file.metadata.frameworks.0.version": "5.16.2",
"appmap.file.metadata.recorder.name": "minitest",
"appmap.file.metadata.test_status": "succeeded",
```
This also fixes an issue where the return value may …
=> fix: `getRecords` now returns nested objects and enforces value type

src/commands/compareSequenceDiagram.ts, src/commands/sequenceDiagram.ts, src/lib/sequenceDiagram.ts
```json
{
"event": "appland.appmap/sequence_diagram:generate",
"metrics": {
"sequence_diagram.num_actors": 6,
"sequence_diagram.num_actions": 50
}
}
```
```json
{
"event": "appland.appmap/sequence_diagram:generate_diff",
"metrics": {
"sequence_diagram.num_actors": 6,
"sequence_diagram.num_actions": 50,
"sequence_diagram.num_changes": 7
}
}
```
=> feat: Emit telemetry for sequence diagrams

src/actions/signup.ts, src/commands/compareSequenceDiagram.ts, src/commands/sequenceDiagram.ts, src/lib/sequenceDiagram.ts, src/telemetry/definitions/events.ts, src/webviews/installGuideWebview.ts
When opening the instructions view and not logged out, the user will no longer see a sign up prompt.
=> fix: Drop the immediate sign-in prompt

src/services/nodeDependencyProcess.ts, src/services/nodeProcessService.ts
Attempt to fix the following type of error we often see in the logs
```
➤ YN0018: │ d3-path@npm:1.0.9: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-selection@npm:1.4.2: The remote archive doesn't match the expected checksum
➤ YN0018: │ crypto-js@npm:4.1.1: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-drag@npm:1.2.5: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-shape@npm:1.3.7: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-timer@npm:1.0.10: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-transition@npm:1.3.2: The remote archive doesn't match the expected checksum
➤ YN0018: │ d3-zoom@npm:1.8.3: The remote archive doesn't match the expected checksum
➤ YN0018: │ …
```
=> fix: Set YARN_CHECKSUM_BEHAVIOR=update when 'yarn up' is called

src/commands/generateOpenApi.ts, src/services/appmapUptodateService.ts, src/services/nodeDependencyProcess.ts, src/services/nodeProcessService.ts
This means we don't need to specify `--ms-enable-electron-run-as-node` or `ELECTRON_RUN_AS_NODE`. It also normalizes logic between remote environments.
Resolves #546
=> fix: Use `child_process.fork` for launching sub-processes

src/services/nodeProcessService.ts, test/integration/nodeProcesses/nodeProcessService.test.ts, test/integrationTest.ts
Presumably some users have a yarn configuration which interferes with our dependency install. This change scrubs the environment of `YARN` configuration which may conflict.
Fixes #553. Integration tests are now run with `YARN_LOCKFILE_NAME` to make sure the override works. Stubbing `process.env` is not possible from the integration test.
=> fix: Override environment yarn configuration

src/appMapService.ts, src/configuration/extensionState.ts, src/editor/appmapEditorProvider.ts, src/extension.ts, src/services/appmapRecommenderService.ts, src/telemetry/definitions/events.ts, test/integration/appmapRecommender/recommender.test.ts
Fixes #537
The first time that a user closes a map, prompt the user to add the AppMap extension to the list of recommended extensions for the current project in extensions.json in the .vscode folder.
If they click `Yes`, then the `extensions.json` file is opened in the editor:
=> Add appmap to recommended extensions

src/services/nodeProcessService.ts
Previously, `yarn up` was not giving the desired outcomes. Some users were not receiving updates. This command ensures both packages are updated while not affecting the version constraints defined in `package.json`.
To see this in action, check the version of `@appland/appmap` or `@appland/scanner` in `yarn.lock`.
On Linux:
```sh
$ cat ~/.config/Code/User/globalStorage/appland.appmap/yarn.lock | grep -A1 '@appland/appmap@npm:^3'
"@appland/appmap@npm:^3":
version: 3.53.0
```
On Darwin:
```sh
$ cat ~/Library/ApplicationSupport/Code/User/globalStorage/appland.appmap/yarn.lock | grep -A1 '@appland/appmap@npm:^3'
"@appland/appmap@npm:^3":
version: 3.53.0
```
Run the extension. The `AppMap: Services` tab in `Output` should indicate success installing dependencies. Checking the version again …
=> fix: Update @appland/appmap and @appland/scanner properly

.vscode/launch.json, src/actions/appmapUploader.ts, src/actions/signup.ts, src/authentication/appmapServerAuthenticationProvider.ts, src/authentication/index.ts, src/configuration/environment.ts, src/extension.ts, src/services/analysisManager.ts, src/services/appMapConfigWatcher.ts, src/services/appmapServerConfiguration.ts, src/services/indexProcessWatcher.ts, src/services/nodeProcessService.ts, src/services/nodeProcessServiceInstance.ts, src/services/processWatcher.ts, src/services/scanProcessWatcher.ts, test/integration/nodeProcesses/backgroundProcess.test.ts, test/integration/nodeProcesses/nodeProcessService.test.ts, test/integration/sampleCodeObjects/codeObjects.test.ts, test/integrationTest.ts, test/system/src/app.ts
* Provide the AppMap API key to the scanner process, so that it can enforce its presence if desired.
* Use a simple interval to manage indexer and scanner processes.
* DRY up access to the AppMap API key.
* Remove some dependency on ProjectState, which isn't reliable as the user adds and removes projects.
=> feat: Put AppMap API key in process env

src/commands/openAppMap.ts, src/commands/openCodeObjectInAppMap.ts, src/commands/openCodeObjectInSource.ts, src/editor/appmapEditorProvider.ts, src/extension.ts, src/lib/buildClassMap.ts, src/tree/classMapTreeDataProvider.ts, src/uri/openAppMapUriHandler.ts, test/integration/editor/opensBySourcePathAndState.test.ts, test/system/src/appMap.ts, test/system/src/appMapWebview.ts, test/system/src/driver.ts, test/system/tests/codeObjects.test.ts
Two main issues are fixed by this pull request:
1. When opening source code, the path was used verbatim. In Java, we only have partial paths (e.g. `myorg/myapp/package/Class.java`) so we should have been using `bestFilePath` when opening those files.
2. We were using URI fragments to send along the view state when opening an AppMap. This works everywhere but on Windows. The `URI` class will not allow us to create a properly formatted `file` URI containing a fragment on this platform. I'm not sure the usage is valid to begin with. Instead, a new command, `appmap.open` has been added to open an AppMap file with a particular state. We now use this instead.
I've added a frontend (system) test to guarantee we're getting visible selection of the intended item, however it seems a bug upstream is …
=> fix: Use best fit path when opening source of a code object

package.json, src/services/nodeProcessService.ts, src/services/processWatcher.ts, test/integration/nodeProcesses/backgroundProcess.test.ts, test/unit/services/processWatcher.test.ts
**This shouldn't be merged until the `wip` commit gets removed. It's only there as a temporary measure to run the integration tests.**
Reduce the cases where the extension scans the entire subtree under the current project directory.
Fixes #633 .
=> fix: reduce scanning for appmap.yml

src/services/processWatcher.ts, test/integration/nodeProcesses/backgroundProcess.test.ts, test/integration/nodeProcesses/processAbort.test.ts, test/integration/nodeProcesses/util.ts
`NodeProcessServiceInstance#startAndStopProcesses` will try to restart services every second. Once the `ProcessWatcher` aborts a failed process, it'll begin restarting every second indefinitely. To resolve this, we'll first check if the process was previously aborted before attempting to start.
This change also adds a test to confirm crashed processes eventually stop spawning. Most of this change is refactoring out some of the testing utility functions into a separate file.
If you prefer to test manually, `kill` the PID of a single process in the `AppMap: Services` output window 4 times. After the fourth time, the process should not restart. The first token in each line is the PID.
```
12380 [Stdout] spawned /opt/vscode/code --ms-enable-electron-run-as-node …
```
=> fix: Don't infinitely retry crashed processes

package.json, src/editor/AppMapDocument.ts, src/editor/appmapEditorProvider.ts, src/telemetry/definitions/errorCodes.ts, yarn.lock
=> Handle large appmaps

package.json, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, src/webviews/signInWebview.ts, web/src/signInView.js, yarn.lock
=> Next sign-in flow experiment

src/commands/installAgent.ts, test/integration/command/installAgent.test.ts
`process.argv0` could sometimes point towards an incorrect binary path
`process.execPath` should be more accurate, and it's now testing for presence of `code` in the command
=> fix: Use a stable node bin path when running the install CLI

src/tree/links.ts
Fixes #686 
The `Troubleshooting` and `FAQ` links are currently broken, so I removed them. We've seen lots of interest in sequence diagrams, so I added a link for that.
Before:
After:
=> Remove broken docs links

package.json, yarn.lock
Fixes #685 
This updates `@appland/components`, which releases this feature to the VS Code marketplace.
=> Users can expand packages in sequence diagram

src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts
Fixes #689 
Adds information about why a project is or is not installable. Specifically, it adds details about how we judge web and test frameworks for a project.
=> Add installability details to telemetry

src/services/watcher.ts
A recent change limited places in which VSCode looks for AppMaps to hardcoded `/{tmp,target,build}/appmap`. This caused it to no longer pick up AppMaps in subprojects of a monorepo.
Now it looks for those directories in the full tree.
=> fix: Look for appmaps in subprojects

src/analyzers/index.ts, src/analyzers/java.ts, src/analyzers/javascript.ts, src/analyzers/python.ts, src/analyzers/ruby.ts, src/analyzers/unknown.ts, src/services/appmapUptodateService.ts, src/services/languageResolver.ts, src/services/projectStateService.ts, src/telemetry/definitions/properties.ts, src/tree/appMapTreeDataProvider.ts, src/tree/findingsTreeDataProvider.ts, src/workspace/installationStatus.ts, src/workspace/projectMetadata.ts, test/integration/index/updateAsAppMapsAreModified.test.ts, test/integration/languageResolver.test.ts, test/integration/projectAnalyzers/javascript.test.ts, test/integration/scanner/performAsAppMapsAreModified.test.ts, test/system/tests/findings.test.ts, test/unit/analyzers/javascript.test.ts
For installation purposes, prefer a language that has a detected web framework. Don't base preference purely on file count statistics.
This fixes a situation in which, once a project has more JS files than web app files (e.g. Ruby), the project picker chooses JS as the install language. 
A couple of other things are included:
1) Use a warning icon when AppMap test_status is `failed`
2) Fix a bug parsing `depends` output
=> fix: Prefer web framework language

package.json, src/appMapService.ts, src/commands/downloadLatestJavaJar.ts, src/commands/updateConfigs.ts, src/configuration/extensionState.ts, src/extension.ts, src/lib/githubRelease.ts, src/services/assetManager.ts, src/services/runConfigService.ts, src/telemetry/definitions/errorCodes.ts, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, test/fixtures/workspaces/project-java/src/main/java/PetClinicApplication.java, test/integration/assetManager/javaJarDownload.test.ts, test/integration/assetManager/javaJarLockfileExists.test.ts, test/integration/runConfigs/runConfigsJava.test.ts, test/integration/runConfigs/runConfigsJavaNoTestExt.test.ts, test/integration/runConfigs/runConfigsRuby.test.ts, test/integration/runConfigs/util.ts, test/integration/util.ts, test/system/tests/findings.test.ts
Fixes getappmap/board#269
This PR helps Java users in VS Code.
* When the extension starts, the latest version of the appmap Java agent JAR will get downloaded to `$HOME/.appmap/java`. This will happen regardless of the language of the project. 
* When a user opens a project, the extension will create a new launch config in `.vscode/launch.json` called `Run with AppMap` that will launch their application with the appmap agent. For this to work, the user must have the [Extension Pack for Java](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) installed. If they don't, then they will see this message when they attempt to use our launch configuration:
* When a user opens a project, the extension will also check to see if they have the [Test Runner for …
=> Run configs for Java users

test/integration/scanner/performAsAppMapsAreModified.test.ts
Fixes a case where AppMaps may not yet be indexed but are expected to be
=> test: Wait for index directory before removing all AppMaps

src/configuration/extensionState.ts, src/editor/appmapEditorProvider.ts, src/services/appmapWatcher.ts, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, test/integration/services/appmapWatcher.test.ts
This PR fixes an issue where project language was being reported as an array of all languages present in the workspace folder. This presented an issue, because there was now no indication of what language the project would be defined as by the project picker.
Resolves #718
=> fix: Project language now reflects the preferred language

src/commands/installAgent.ts, test/integration/command/installAgent.test.ts
This is related to the discussion in https://github.com/getappmap/appmap-js/issues/1207
=> feat: Ensure the latest cli version is used when installing agent in JS

package.json, src/configuration/extensionSettings.ts, src/editor/appmapEditorProvider.ts, web/src/appmapView.js
Add (again) the flamegraph extension flag. This has nothing to do with the bug that got introduced by importing conflicting d3 dependencies and caused the main panel to become unresponsive.
=> feat: add flame graph setting

src/commands/getAppmapDir.ts, src/extension.ts, src/services/runConfigService.ts, test/integration/runConfigs/runConfigsJava.test.ts, test/integration/runConfigs/testConfigsJava.test.ts, test/integration/runConfigs/util.ts
Fixes #730
`runConfigs/testConfigsJava.test.ts`.
=> Java test config respects appmap_dir

src/extension.ts
Fixes #742 
This change makes it so that the appmap sidebar is opened to the sign-in page when the extension is installed. 
If the user is already signed-in, then the sign-in page won't be visible and the command will do nothing.
=> Open appmap sign-in on installation

.vscode/launch.json, package.json, src/actions/remoteRecording.ts, src/extension.ts, src/webviews/installGuideWebview.ts, test/unit/actions/remoteRecording.test.ts, test/unit/mock/vscode/commands.ts, test/unit/mock/vscode/index.ts, test/unit/mock/vscode/window.ts, test/unit/mock/vscode/workspace.ts
Fixes #734
This PR makes it so that the AppMaps generated in a remote recording are stored in the `appmap_dir` specified in the `appmap.yml` configuration file. 
As discussed recently, we want to move away from the VS Code integration tests and towards unit tests, so the tests for the changes in this PR are unit tests. Also, a launch config was added for the unit tests, so that breakpoints can be used when writing/debugging unit tests.
=> Remote recording respects `appmap_dir` in `appmap.yml`

src/tree/appMapTreeDataProvider.ts, test/integration/appmaps/appmapsTree.test.ts
Fixes #744 
Using a workspace with both `spring-petclinic` and `sample_app_6th_ed` open:
Before:
After:
=> AppMaps are organized by workspace in tree view

src/commands/deleteAllAppMaps.ts, src/extension.ts, src/lib/deleteAppMap.ts, src/lib/deleteAppMaps.ts, src/lib/deleteFolderAppMaps.ts, src/services/appmapCollection.ts, src/services/appmapCollectionFile.ts, src/tree/contextMenu.ts, test/integration/lib/indexJanitor.test.ts, test/unit/lib/deleteAppMap.test.ts, test/unit/lib/deleteFolderAppMaps.test.ts, test/unit/mock/vscode/index.ts, test/unit/mock/vscode/workspace.ts
This PR addresses two issues with deleting AppMaps:
1. When right clicking on a project within the 'AppMaps' sidebar tree, the 'Delete AppMaps' option would do nothing. This has been resolved.
3. When using the `deleteAppMap` function, it was possible for empty index directories to be left behind. If an AppMap wasn't acknowledged through a file system event, the IndexJanitor would fail to clean up any index directories. With this fix, such directories will be deleted immediately if they've yet to be imported into the AppMap collection.
=> AppMap deletion bug fixes

package.json, yarn.lock
Fixes #766 
Also, update @appland/models to 2.6.3. 
These changes will release a fix where fqids were inconsistent between VS Code and @appland/models, which caused a bug where selecting a SQL query or HTTP request from the code object tree opened the correct appmap, but the map did not have the correct code object selected.
=> Update @appland/components to 2.57.0

package.json, yarn.lock
Fixes #775 
Upgrade `@appland/components` to 2.58.1 to fix the instructions, which previously incorrectly specified the JVM arg to include the java agent.
=> Update java jar instructions

package.json, src/diagnostics/findingsDiagnosticsProvider.ts, src/webviews/findingInfoWebview.ts, test/integration/scanner/populateDiagostics.test.ts, yarn.lock
Fixes #789 
Previously, when opening an AppMap from the findings webview:
It would open to the `Trace View`:
This change makes it so that it opens the AppMap to the finding:
=> Select finding when opening map

package.json
=> Top level of runtime analysis tree is expanded by default

package.json, src/tree/contextMenu.ts
Fixes #621 
We don't need this since we have sequence diagrams built in to the AppMap view.
=> Remove generate sequence diagram option for appmap

test/system/src/app.ts
Temporarily lock system tests to VS Code version 1.81.1 (same as integration tests)
=> Lock system tests to vs code version 1.81.1

src/authentication/appmapServerAuthenticationProvider.ts, src/extension.ts, src/webviews/signInWebview.ts
Fixes #792 
Previously, when signing in, if a user got this menu:
And then instinctively hit `Cancel` (as happened on a customer call), then they would get this progress menu in the bottom right corner:
If a user then hits the `Sign In` button again, nothing will happen as long as that progress menu is open. They have to hit the `Cancel` button on the progress menu before they can attempt to sign in again. This is a problem because it's easy to not notice the progress menu.
This PR makes it so that clicking the `Sign In` button automatically cancels any previous sign-in attempts and re-starts the sign-in process.
1. If you are signed in with AppMap Server, please sign out using the accounts button in the bottom left corner:
2. Click on the big blue Sign In button and then click Allow:
3. …
=> Clicking sign-in button cancels previous sign-in attempt

src/authentication/appmapServerAuthenticationProvider.ts, src/extension.ts, test/integration/authentication/appmapServerLogin.test.ts
`AppMap Server` is misleading, because it's really an account management provider and not an "API Server".
Rename the `AppMap Server` auth provider to `AppMap`.
=> feat: Rename AppMap auth provider to 'AppMap'

src/webviews/installGuideWebview.ts, test/system/src/driver.ts, test/system/tests/instructions.test.ts
Resolves https://github.com/getappmap/appmap-js/issues/1386
To reproduce:
- `Ctrl+K F` will close the current workspace/folder
- Open any instructions page
=> fix: Always show 'no projects found' when viewing instructions if no project is open

src/lib/deleteAppMaps.ts, src/services/appmapCollection.ts, src/services/appmapCollectionFile.ts, src/tree/contextMenu.ts, test/integration/command/deleteAppMap.test.ts
Fixes: #799 
feat(deleteAppMaps.ts): add closeEditorByUri function after deleting appmaps
feat(contextMenu.ts): update deleteAppMap command to handle absence of item object
feat(deleteAppMap.test.ts): add new integration test for deleteAppMap
fix(closeEditorByUri.test.ts): fix test to include input conditions
=> Consistent delete behavior from command palette

src/lib/deleteAppMap.ts
Fixes: #833 
feat(deleteAppMap.ts): ensure reliable delete event emission by adding retry on metadata.json removal
=> Emit delete appmap event reliably

package.json, src/authentication/appmapServerAuthenticationProvider.ts, src/configuration/extensionSettings.ts, src/extension.ts, src/services/findingLocation.ts, src/services/findingsIndex.ts, src/uri/appmapServerAuthenticationHandler.ts, yarn.lock
User can enter license key directly.
After signing in, the user may need to (will always need to?) "Grant access to AppMap (the auth provider) to AppMap (the extension)". Once doing this, the AppMap sidebar should switch from showing the Sign In prompt to showing the AppMaps.
[appmap-0.104.0-license-key-command.vsix.zip](https://github.com/getappmap/vscode-appland/files/13517510/appmap-0.104.0-license-key-command.vsix.zip)
=> feat: Enter license key

package.json, src/configuration/extensionSettings.ts, src/services/processWatcher.ts, src/webviews/chatSearchWebview.ts, web/src/chatSearchView.js
This is necessary to make authenticated HTTP requests, such as providing message feedback.
=> Authenticate the chat search frontend

.travis.yml, package.json, test/integrationTest.ts, test/mocks/mockExtensionContext.ts, test/system/src/app.ts, test/system/src/appMap.ts, test/system/tests/findings.test.ts, test/system/tests/instructions.test.ts, yarn.lock
This is the first version of VSCode that ships Node 18.
This will affect approx. 10% of users who are running < v1.82.0.
=> feat: Update VSCode engine to v1.82.0

.travis.yml, package.json, src/services/nodeProcessService.ts, test/integrationTest.ts, test/mocks/mockExtensionContext.ts, test/system/src/app.ts, test/system/src/appMap.ts, test/system/tests/findings.test.ts, test/system/tests/instructions.test.ts, yarn.lock
This change should address issues downloading service dependencies among users who have set `http.proxy`. Previously, yarn would attempt to upgrade dependencies without a proxy.
Please note that this is a hot fix, and is merging with `master`.
=> hotfix: Propagate `http.proxy` setting to Yarn

package.json, web/src/chatSearchView.js, yarn.lock
=> fix: Add code block syntax highlighting

.appmapignore, src/lib/findFiles.ts, src/services/appmapConfigManager.ts, test/unit/services/appmapignoreManager.test.ts
Adds the ability to specify directories to ignore using an `.appmapignore` file in the root of a project. It follows the same syntax for directories that `.gitignore` uses. So, a line containing `test` will ignore all directories containing `test`, while a line containing `/test` will ignore the `test` directory in the root folder of the project only.
=> Use `.appmapignore` to ignore certain directories

src/actions/remoteRecording.ts, src/authentication/appmapServerAuthenticationProvider.ts, src/configuration/extensionState.ts, src/extension.ts, src/lib/selectIndexProcess.ts, src/services/analysisManager.ts, src/services/appmapCollectionFile.ts, src/services/appmapConfigManager.ts, src/services/appmapUptodateService.ts, src/services/indexProcessWatcher.ts, src/services/lineInfoIndex.ts, src/services/nodeProcessService.ts, src/services/processWatcher.ts, src/services/scanProcessWatcher.ts, src/services/sourceFileWatcher.ts, src/tree/appMapTreeDataProvider.ts, src/tree/classMapTreeDataProvider.ts, src/tree/findingsTreeDataProvider.ts, src/tree/instructionsTreeDataProvider.ts, src/tree/linkTreeDataProvider.ts, src/uri/appmapServerAuthenticationHandler.ts, src/webviews/chatSearchWebview.ts, src/webviews/filterStore.ts, test/integration/appmapConfigManager/appmapConfigManager.test.ts, test/integration/explain/explain.test.ts, test/unit/lib/selectIndexProcess.test.ts, test/unit/mock/vscode/window.ts, test/unit/services/processWatcher.test.ts
When there are multiple appmap.yml in a workspace, the user must be prompted to choose which one they want to use for their question. Each appmap.yml will correspond to a Navie RPC port, to which the question should be directed.
If there are no workspaces open with appmap.yml, then as before the Explain command won't run.
If there is exactly one index process with a ready RPC port, then this process is selected.
Otherwise, the user is prompted to choose which directory they want to run the Explain command in.
Fixes #869
=> feat: Navie prompts the user to choose a directory

package.json, src/webviews/appmapMessageHandler.ts, web/src/handleAppMapMessages.js, yarn.lock
Integrates the "Export JSON" option from the AppMap. The data is saved to a temp file and opened in the system File Explorer / Finder. The data can then be drag-and-dropped over into Confluence, or any other system that accepts AppMaps / JSON files. The view filter and prune settings are embedded in the exported file, so they will be restored by the AppMap diagram when the file is opened.
This is not updated with the styling changes to the Export menu, but it shows the flow:
https://www.loom.com/share/64b87bad09004ca0978a5f4cee8e070a
[appmap-0.105.0.vsix.zip](https://github.com/getappmap/vscode-appland/files/14113213/appmap-0.105.0.vsix.zip)
Related (pre-requiste): https://github.com/getappmap/appmap-js/pull/1532
=> feat: Handle exportJSON message from AppMap

.vscode/launch.json, src/configuration/environment.ts, src/util.ts
Fixes #660 
This was working as expected but it was difficult to mimic a new installation in our dev environment. This change makes it so that using `AppMap: Reset Usage State` will create a mimic of a new installation after reloading the Extension Host window.
=> Mimic new install in dev env

package.json, src/extension.ts, src/webviews/getWebviewContent.ts, src/webviews/signInWebview.ts, web/src/appmapView.js, web/src/signInView.js, yarn.lock
This incorporates the new `Activate AppMap` webview in place of the `Sign In` webview from [this PR](https://github.com/getappmap/appmap-js/pull/1620). It also handles the `activate` message from the webview that activates a user based on their email.
=> Users can activate with email

src/commands/installAgent.ts, test/integration/command/installAgent.test.ts
Fixes #913 
Only add the `--ms-enable-electron-run-as-node` flag for versions of VS Code prior to 1.86.0.
=> CLI installer fix

src/commands/installAgent.ts, test/integration/command/installAgent.test.ts
For versions of VS Code prior to 1.86.0, we need to apply the --ms-enable-electron-run-as-node flag when we start the CLI installer. We do not need this flag on version 1.86.0 or later.
=> Apply appropriate flags to CLI installer

package.json
Update the text that appears in the IDE when you search for AppMap:
This is the old text, I'm not sure how to get a preview of the new text.
=> Include Navie in VS Code extension description

package.json, src/commands/commandRegistry.ts, src/commands/quickSearch.ts, src/editor/appmapEditorProvider.ts, src/webviews/chatSearchWebview.ts, web/src/appmapView.js, web/src/chatSearchView.js, yarn.lock
Fixes getappmap/board#316
Handles messages and props related to [this PR](https://github.com/getappmap/appmap-js/pull/1636) so that users can open Navie from within an AppMap and ask about it.
`appmapFsPath`: Pass this prop to the AppMap webview when opening. It is the file system path of the AppMap. This is required for this feature to work correctly.
`ask-navie-about-map`: This is emitted when a user clicks on the `Ask Navie` button in an AppMap. It will have one parameter `mapFsPath`, which is the file system path of the appmap. To handle this message:
1. Read the AppMap data from the specified file path.
2. Open Navie, passing the props `targetAppmapData` and `targetAppmapFsPath`. `targetAppmapData` is the AppMap data that was just read from the file and `targetAppmapFsPath` is …
=> Open Navie from an appmap

src/webviews/filterStore.ts
I noticed this error when I was working on something else recently:
```
stack trace: TypeError: Cannot read properties of undefined (reading 'map')
at FilterStore.saveFilter (/home/ahtrotta/projects/appmap/vscode-appland/src/webviews/filterStore.ts:36:33)
at w.value (/home/ahtrotta/projects/appmap/vscode-appland/src/webviews/appmapMessageHandler.ts:85:21)
at n.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
at n.z (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1972)
at n.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2188)
at E.$onMessage (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:142:14051)
at s.S …
```
=> Retrieving saved filters always returns an array

package.json, src/configuration/extensionSettings.ts, src/services/appmapConfigManager.ts, src/services/rpcProcessWatcher.ts, src/services/watcher.ts
This is used for development, running byok Navie in a separate local process or debugger.
Run the command `appmap rpc` (e.g. in a debugger), then you can set the port as a VSCode option and "Ask Navie" windows will connect to your running `rpc` command instead of the `rpc` helper command managed by VSCode.
=> feat: Enable configuration of the Navie / JSON-RPC port

package.json, src/configuration/extensionSettings.ts, src/services/processWatcher.ts, test/unit/services/processWatcher.test.ts
Also, if Azure OpenAI configuration is detected in the configured environment, use the OpenAI key from secrets storage for it.
=> feat: Allow configuring CLI environment

src/assets/assetDownloader.ts, src/assets/assetService.ts, src/assets/index.ts, test/unit/assets/appmapCliDownloader.test.ts
Windows won't spawn a process unless it has the magical `exe` file extension. The secondary benefit of this pull request is it'll always restore missing symlinks, regardless of platform.
=> fix: Windows binaries properly use the .exe extension

package.json, test/system/src/appMap.ts, test/system/tests/findings.test.ts, test/system/tests/instructions.test.ts
* Add a `NAVIE` section to the sidebar containing a large blue button that opens the Navie chat interface.
* Rename `INSTRUCTIONS` to `APPMAP RECORDING INSTRUCTIONS`.
* Rename `APPMAPS` to `APPMAP DATA`.
* Change the text and button when there is no AppMap data.
* Make the instructions and runtime analysis sections collapsed by default.
* Show the same `AppMap is inititalizing...` message for all of the sidebar sections.
=> Add a Navie section to the sidebar

resources/versions.json, src/services/chatSearchDataService.ts, src/services/rpcProcessService.ts, src/webviews/chatSearchWebview.ts, test/unit/mock/vscode/Selection.ts, test/unit/mock/vscode/index.ts, test/unit/mock/vscode/window.ts, test/unit/services/chatSearchData.test.ts
Propagate code selection to Navie. 
Select code:
Open Navie, the code selection is populated the same way as if you'd used the light bulb:
=> feat: Send active code editor selection to Navie

test/integration/command/deleteAppMap.test.ts, test/integration/command/openAsJson.test.ts
Add tests to ensure deleteAppMap and openAsJson fail if the active tab isn't an AppMap.
=> test: test command failures, too

src/services/rpcProcessWatcher.ts
Once set, the RPC port was not able able to change after a service restart. This could happen after a crash or change in authentication state.
=> fix: Fix a case where the RPC port would not properly assign after reload

src/authentication/index.ts, src/extension.ts
This change handles cases where `vscode.authentication.getSession` may time out waiting for the authentication provider to register. Upon initialization, we immediately request a session, however we don't initialize the authentication provider until we're halfway through activation.
Just handling this error is enough to fix the issue, however I've also moved the authentication provider's initialization to the top of activation to fix a cosmetic issue. On its own, this may have been enough to fix the issue, but catching the exception is a guarantee.
=> fix: Authentication provider timeouts

package.json, src/configuration/extensionSettings.ts, src/extension.ts, src/services/nodeProcessService.ts, test/fixtures/workspaces/project-a/.vscode/settings.json, test/fixtures/workspaces/project-several-findings/.vscode/settings.json, test/fixtures/workspaces/project-system/.vscode/settings.json, test/integration/scanner/settingsDefault.test.ts
Fixes #973.
- Adds "Enable AppMap scanner" to the extension settings to enable/disable `scanner` process with the default value of `disabled`.
- Change is applied only after restart.
- Adds a test to verify the new setting.
- Adds `scannerEnabled: true` setting to the fixture projects which are used in the tests assuming `scanner` is running by default.
=> feat: Scanner is disabled by default

src/webviews/installGuideWebview.ts, test/mocks/mockExtensionContext.ts, test/unit/commands/quickSearch.test.ts, test/unit/mock/vscode/EventEmitter.ts, test/unit/mock/vscode/workspace.ts, test/unit/services/chatSearchData.test.ts, test/unit/services/processWatcher.test.ts
Lowering the `@types/vscode` version introduced some eslint errors
=> Fix eslint

package.json, src/analyzers/java.ts, src/analyzers/javascript.ts, src/analyzers/python.ts, src/analyzers/ruby.ts, test/unit/analyzers/javascript.test.ts, yarn.lock
Updates @appland/components to include the most recent recording instructions for Java, Ruby and Python. Also fixes some cosmetic casing issues with dependencies.
=> Update recording instructions

package.json, src/configuration/extensionSettings.ts, src/extension.ts, src/services/chatCompletion.ts, src/services/processWatcher.ts, test/unit/mock/vscode/CancellationTokenSource.ts, test/unit/mock/vscode/LanguageModelChatMessage.ts, test/unit/mock/vscode/index.ts, test/unit/mock/vscode/lm.ts, test/unit/services/chatCompletion.test.ts
This adds a config option to use VSCode LLM API. Note it's hardcoded for Copilot for now for simplicity.
By implementing an OpenAI-compatible API on top of the VSCode LM API it can be used without any changes to CLI. 
Small cosmetic changes to components are in https://github.com/getappmap/appmap-js/pull/1881 , but they're not required for this to work. However, please don't merge this until that one is merged and the components version is bumped here.
=> feat: Allow use of VSCode LLM API

src/services/nodeDependencyProcess.ts
When using the development option to provide path to appmap-js package childProcess.fork has been used which caused it to use VSCode node. This has worked well in the past but recently we've started using binary extensions which can't load across different Node versions. This has rendered this option all but unusable unless you used the same exact Node version that VSCode uses to compile the dependencies.
This change makes this flow use spawn('node') instead of fork(), using system node which presumably should be available in a development environment and has a better chance of being the correct version.
Note this should affect any users since unless this development config option is used they should be running precompiled CLI binaries.
=> fix: Use system node when spawning AppMap tools in development

package.json, src/webviews/chatSearchWebview.ts, web/src/chatSearchView.js, yarn.lock
Instead of destructively clearing the current chat, "new chat" button opens a new tab instead.
Requires support in @appland/components provided by https://github.com/getappmap/appmap-js/pull/1925
=> fix: "New chat" button opens a new chat

.vscode/launch.json, src/extension.ts, src/services/environmentVariableService.ts, src/services/rpcProcessService.ts, src/services/rpcProcessWatcher.ts, test/unit/services/rpcProcessService.test.ts
The pull request includes the following changes:
1. **Disable Extensions on Launch**: The launch configuration for the extension now includes the `--disable-extensions` argument, which disables other extensions when running the AppMap extension for development.
2. **Environment Variable Service Improvements**: The `EnvironmentVariableService` has been updated to handle configuration changes more efficiently. Instead of reloading the entire window, it now restarts the RPC server when the `appMap.commandLineEnvironment` configuration changes. The restart is debounced to prevent multiple restarts during rapid configuration changes.
3. **RPC Process Restart**: The `RpcProcessService` now includes a `restart` method, which allows restarting the RPC server process without reloading the entire …
=> Restart RPC server when environment variables are modified

.github/workflows/ci.yml, package.json, src/extension.ts, src/services/chatCompletion.ts, src/services/rpcProcessService.ts, test/unit/services/chatCompletion.test.ts
This addresses an issue where the application would hang if the Copilot service encountered an error during streaming. This could happen, for example, when a message is too long. The fix ensures that such errors are caught and reported correctly to the client, preventing a broken connection. Additionally, the HTTP status code for these errors has been changed to 422, indicating that the issue is likely non-recoverable and the client should not retry.
1. **Error Handling in `streamChatCompletion`**:
- Added a `try-catch` block to handle errors during streaming.
- If an error occurs, it now sends a 422 status code and the error message to the client.
```typescript
async function streamChatCompletion(
res: ServerResponse,
model: LanguageModelChat,
result: LanguageModelChatResponse
) {
try { …
```
=> Don't hang on error when streaming Copilot response

src/assets/assetService.ts, src/services/rpcProcessService.ts, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts
E.g.:
```
{
"event": "appland.appmap/debug/exception",
"properties": {
"appmap.debug.exception": "Error: appmap rpc --port 0 exited with code 1",
"appmap.debug.error_code": "ProcessFailure",
"appmap.debug.log": "Stderr: --navie-provider option not provided, and none of OPENAI_API_KEY AZURE_OPENAI_API_KEY ANTHROPIC_API_KEY are available. Using remote Navie provider.\n\nStderr: Detected code editor: vscode\nSetting RPC configuration: {\"projectDirectories\":[\"\"],\"appmapConfigFiles\":[\"\"]}\n\nStderr: [Error: ENOENT: no such file or directory, scandir '.appmap/navie/history'] {\n  errno: -2,\n  code: 'ENOENT',\n  syscall: 'scandir',\n  path: '.appmap/navie/history'\n}\n",
"appmap.debug.version": "3.163.4"
}
}
```
=> fix: Log errors that would prevent Navie from servicing requests

.gitignore, .navie/prompts/pr_description.md, .navie/prompts/review_vs_plan.md, package.json, src/configuration/extensionSettings.ts, src/services/chatCompletion.ts, test/unit/services/chatCompletion.test.ts
1. **Configuration Storage**: Introduced `appMap.navie.contextTokenLimit` to `package.json` and `extensionSettings.ts`. This new configuration item sets a default size for the context tokens sent to Navie AI, ensuring that the relevant token size constraints are respected.
1. **Chat Completion Handling**:
- Updated `chatCompletion.ts` to use the `navieContextTokenLimit` configuration to dynamically determine the token limit.
- Adjusted the environment variable `APPMAP_NAVIE_TOKEN_LIMIT` based on both the LLM default and the user-defined setting.
1. **Testing**: Added unit tests for `chatCompletion.ts` to validate the behavior of the `navieContextTokenLimit` configuration, ensuring the limit is applied correctly based on different configurations.
The default for the user-assigned token …
=> feat: Token limit setting

README.md
@kgilpin called out missing commands which I added.  
Do we want to update the examples?  We've got an end to end Navie video now - do we want to embed or link to this video? 
https://vimeo.com/1012769182
=> fix: Update the VS Code marketplace extension readme. 

src/services/chatCompletion.ts, test/unit/services/chatCompletion.test.ts
Previously the server would report an error stating `Message exceeds token limit.`.
This error is now transformed into an OpenAI API compatible error, mimicking the same error returned by the official OpenAI API. This change allows Navie to properly reduce the token count before trying again.
=> fix: Write an OpenAI-compatible error when context overflows

src/util.ts, test/unit/util.test.ts
When opening a sequence diagram from context, paths were being improperly handled on Windows.
=> fix: Fix an issue when opening sequence diagrams from Navie on Windows

package.json, src/extension.ts, src/lib/once.ts, src/services/chatCompletion.ts, src/services/navieConfigurationService.ts, src/services/processWatcher.ts, src/services/rpcProcessService.ts, src/webviews/chatSearchWebview.ts, test/unit/mock/vscode/workspace.ts, test/unit/services/chatCompletion.test.ts, test/unit/services/rpcProcessService.test.ts, web/src/chatSearchView.js, yarn.lock
Changes the default to true and changes the flow a bit (this is executed on initialization and on state change):
- If Copilot backend is enabled:
- if Copilot is available, use it;
- when it becomes unavailable, switch to default;
- if LM not available (old VSCode), fall back to default backend;
- if Copilot is not available, suggest installation;
- when it becomes available, switch to it;
- else:
- show informational message if user manually disabled it.
Note for all these messages are shown only once, unless the state change is caused by user action.
Other changes:
- wording changes to reference Copilot instead of generic LM (we only really support it currently anyway),
- make sure to restart Navie backend as necessary and without debouncing (which is only really necessary when changing …
=> feat: Enable Copilot by default if available

src/webviews/chatSearchWebview.ts
Use vscode.Uri.file to parse file paths, rather than vscode.Uri.path.
Fixes #1040 .
=> fix: parse pinned file paths correctly

web/src/app.js
Once triggered, this frequently enters into an infinite loop where focus is set every 200ms, causing the input to drop keystrokes.
=> fix: Drop the automatic input focus

src/services/rpcProcessService.ts, src/util.ts, src/webviews/chatSearchWebview.ts, web/src/chatSearchView.js
Using the event emit in the recent [`@appland/components` update](https://github.com/getappmap/appmap-js/blob/main/packages/components/CHANGELOG.md#applandcomponents-v4400-2024-10-28), links to files will now be opened from a Navie chat.
=> fix: File links can now be clicked in Navie responses

src/configuration/extensionSettings.ts
This fixes an issue where the default model would not be applied if the preferred model was an empty string. It also writes the configuration to the global state, instead of workspace settings.
=> fix: Default applys to empty string in `copilot.preferredModel`

src/configuration/extensionState.ts, test/unit/extensionState.test.ts
`ExtenstionState.insalledPriorTo` uses `semver.lt(firstVersion, version)` to check if the extension was first installed before a given version (this is for the purposes of displaying walkthrough on start). The default value of `firstVersion` is `unknown`, which is not a valid version so causes semver to crash.
I changed it to verify the inputs and return `true` in case of `unknown` — this is on the assumption that if the version was too old to set the version it must have been older than any version we care about.
=> Fix a bug in ExtensionState caused by unknown first installed version

src/webviews/chatSearchWebview.ts
The drive letter would be URI encoded (e.g., `c%3A`) preventing the URI from being parsed.
Fixes https://github.com/getappmap/vscode-appland/issues/1067
=> fix: Fix an issue which broke pinned files on Windows

src/services/chatCompletion.ts, test/unit/mock/vscode/lm.ts, test/unit/mock/vscode/window.ts, test/unit/services/chatCompletion.test.ts
This pull request introduces several changes to improve the initialization and testing of the `ChatCompletion` class in the `src/services/chatCompletion.ts` file. The most important changes include adding an initialization flag, modifying the configuration check to wait for models to settle, and enhancing the mock and unit test files to support these changes.
Improvements to `ChatCompletion` class initialization:
* Added a static `initialized` flag to the `ChatCompletion` class to track whether the initialization process has completed. (`src/services/chatCompletion.ts`)
* Modified the `checkConfiguration` method to wait for models to settle if the `initialized` flag is not set, allowing the extension to load correctly even if it starts before Copilot. (`src/services/chatCompletion.ts`) …
=> fix: Wait for lm models to settle when initializing

package.json, web/src/app.js, yarn.lock
This drops the hacky focus content in favor of the input focus implementation in `@appland/components`. It also pins `node-gyp` to major version 10, as v11 fails to build some of our native dependencies while on the current Node LTS.
=> chore: Update @appland/components to v4.44.0

package.json, src/commands/openNavieHistory.ts, src/extension.ts, src/services/rpcProcessService.ts, src/webviews/chatSearchWebview.ts, src/webviews/getWebviewContent.ts, test/integration/chat/chat.test.ts, tsup.config.ts, web/src/chatSearchView.js, yarn.lock
This pull request introduces the ability for users to access and reopen their past Navie chat conversations.
**Changes:**
*   **New Command:** Adds a new command, `AppMap: Open Navie History`, accessible via the command palette.
*   **History Retrieval:** When invoked, the new command communicates with the backend RPC service (`v1.navie.thread.query`) to fetch a list of recent Navie conversation threads.
*   **User Interaction:** The fetched history is presented to the user in a Quick Pick list, showing conversation titles (or "Untitled") and creation dates.
*   **Reopening Conversations:** Selecting a conversation from the list triggers the existing `appmap.explain` command, passing the selected `threadId`.
*   **Webview Integration:** The chat search webview (`chatSearchWebview`) has …
=> feat: Integrate Navie history

src/services/navieConfigurationService.ts
This addresses an issue where if the user had an old-style OpenAI API key stored in secrets, it'd overwrite the value in the secret env.
=> fix: Only migrate OpenAI API key once

package.json, src/services/chatCompletion.ts, test/unit/services/chatCompletion.test.ts, yarn.lock
- Makes the completion service send 400 on token overflow; this aligns with what OpenAI sends and prevents clients (like langchain) from retrying.
- Makes token count work in some versions of vscode where message `content` is not a string.
- Drive by change to remove unused (afaict) dependency on `@appland/appmap` which brings in a lot of other dependencies.
=> Completion service fixes

src/services/resolvedFinding.ts
This PR addresses an issue where some AppMap findings were not appearing in the VSCode sidebar. The root cause was an "Illegal argument: line must be non-negative" error, which occurred when processing finding locations with invalid line numbers (e.g., filename:0, filename:, or filename:-1).
The resolvePathLocation function was attempting to use these invalid line numbers, leading to a rejected promise that prevented the associated findings from being displayed.
Changes:
Modified resolvePathLocation in src/services/resolvedFinding.ts to:
Explicitly parse the line number string to an integer.
Validate that the parsed line number is a positive integer (> 0).
If an invalid line number is detected (non-numeric, zero, or negative), it now defaults to line 1 and logs a warning to the console …
=> fix: Gracefully handle invalid line numbers in finding stack traces

package.json, src/commands/quickReview.ts, src/extension.ts, test/unit/commands/quickReview.test.ts, test/unit/mock/vscode/commands.ts, test/unit/mock/vscode/index.ts, web/src/chatSearchView.js
Adds a new command `appmap.navie.quickReview` that allows users to select a Git reference (branch, tag, or commit) as a base and initiate an AI-driven code review of the changes relative to that base via Navie. Integrates the command into the Navie view and commands palette. Includes necessary mocking and unit tests for the new command.
=> Implement AI-driven quick review command

.github/workflows/ci.yml, DEVELOPMENT.md, build/bundleConfig.md, build/bundleConfig.ps1, build/updateResources.js, doc/assets.md, doc/telemetry.md, package.json, resources/versions.json, src/assets/assetService.ts, src/assets/index.ts, src/authentication/appmapServerAuthenticationProvider.ts, src/commands/downloadLatestJavaJar.ts, src/commands/generateOpenApi.ts, src/commands/installAgent.ts, src/configuration/extensionSettings.ts, src/editor/appmapEditorProvider.ts, src/extension.ts, src/services/appmapUptodateService.ts, src/services/nodeProcessService.ts, src/services/rpcProcessService.ts, src/services/rpcProcessWatcher.ts, src/telemetry/index.ts, src/telemetry/splunkTelemetryReporter.ts, src/webviews/signInWebview.ts, test/unit/assets/appmapCliDownloader.test.ts, test/unit/assets/assetService.test.ts, test/unit/assets/javaAgentDownloader.test.ts, test/unit/assets/mockAssetApis.ts
This pull request introduces a major refactoring of the tool asset management system, significantly improving how the AppMap CLI, Scanner, and Java agent are downloaded, cached, and referenced. It also includes new configuration options and the integration of a new telemetry backend.
This PR integrates support for **Splunk telemetry**, including the necessary configuration options. This feature was developed in a different project and is now being merged to expand the available telemetry backends for clients.
The entire system for handling external tool binaries has been re-architected. Key changes include:
* **Platform-Appropriate Caching:** Tools are now downloaded to a dedicated, platform-appropriate cache directory.
* **Symbolic Links:** Creation of robust symlinks in `~/.appmap/bin` …
=> Overhaul tool asset management and add Splunk telemetry support
