getappmap/vscode-appland

media/scenario.css
Styling updates for inputs & tabs
=> styling for inputs & tabs

media/scenario.js, media/ui/classDetails.js, media/ui/codeObjectDetails.js, media/ui/functionDetails.js, package-lock.json, package.json, src/scenarioViewer.ts
List functions of a class:
Clicking a function replaces the class details with the function details:
User can open function source to line:
=> Enhance code object details

media/scenario.js, media/ui/classDetails.js, media/ui/codeObjectDetails.js, media/ui/functionDetails.js, src/scenarioViewer.ts
https://www.loom.com/share/a979c567b2f14d389aee08358626aad1
=> Link function to call events and back to its class

src/databaseUpdater.ts, src/extension.ts, src/scenarioViewer.ts, src/scss/_global.scss, src/util.ts, types/@appland/index.d.ts
- Design matches the Figma doc. closes #30 
- Sidebar scrolls when necessary. closes #22 
[Figma ->](https://www.figma.com/file/BqZuGL8egIF37cgbvrz1Xm/vscode?node-id=112%3A0)
[Loom ->](https://www.loom.com/share/236da524162c4277bdfd683c237f7239)
=> Extension style matches the Figma doc

package.json
The `description` attribute in package.json was updated with a new summary text.
=> Update description with new executive summary

src/scenarioViewer.ts
This handles two edge cases:
* When the project has source files in subdirs of the main dir
* When appmap-ruby reports absolute paths to Gem files
=> Search for source files by relative path

README.md
@ptrdvrk Updated setup instructions, please review.
=> Update the setup instructions, add animated Gif for Ruby

README.md, package-lock.json
Elizabeth provided a new text for the initial paragraph.
=> Update readme opening

README.md, package.json
The title and 1st paragraph updated.
=> Update topline message

package-lock.json, package.json
Update `@appland/appmap` from `v1.1.1` to `v1.1.2`
=> feat: update @appland/appmap to v1.1.2

README.md
A visible typo fixed in README.md
=> fix: documentation improvements

README.md, package.json
Replaced positioning with a new text by EL 
Added a note about arrow keys navigation in the Trace
Updated the AppMap description in package.json
=> Doc updates

README.md
README.md changes:
- Sharing instructions updated
- Python and Ruby getting started 2 1/2 minute videos
=> fix: sharing instructions, setup videos

doc/TUTORIAL-JAVA-PETCLINIC.md
Java step-by-step tutorial using the new Maven plugin
=> Tutorial java petclinic with Maven plugin

doc/TUTORIAL-PYTHON-CHIPYORG.md
Fixes a missing \n that breaks the formatting around the video.
=> Chipy doc patch

README.md, doc/TUTORIAL-JAVA-PETCLINIC.md
Doc update:
- maven instructions updated
- default output for maven plugin is now target/appmap
- updated loom video with pom.xml
- updated tutorial with pom.xml
=> Docs java update

README.md
=> docs: added missing SHIFT in search config

package-lock.json, package.json, src/scenarioViewer.ts, web/src/app.js
Fixes: https://github.com/applandinc/appmap-js/issues/136
=> fix: Show AppMap instructions on extension first open

package-lock.json, package.json, src/scenarioViewer.ts, web/src/app.js
=> Add commands to read/write AppMap state

src/telemetry.ts
=> feat: send event count as metrics

package.json, src/appmapUploader.ts
AppLand Server -> AppMap Cloud
=> Small update texts in prompts and labels

src/extension.ts, src/tree/milestoneTreeDataProvider.ts
This update is meant for the UX testing exercise. We should have similar functionality for GA, but only open the Quickstart the first time.
=> Quickstart auto-open after init

src/databaseUpdater.ts
=> fix: add possible folders with appmaps to file watcher

src/appmapCollectionFile.ts
=> fix: finish extension initialization when no workspace is open

package.json, src/scenarioViewer.ts
=> fix: show update notification only when extension was updated

src/projectWatcher.ts
=> fix: set steps 3 and 4 incomplete when steps 1 or 2 are completed

src/languageResolver.ts
=>  fix: Only return supported languages when identifying project language

package.json
=> fix: Replace `Install AppMap agent` button

src/scenarioViewer.ts
Fixes https://github.com/applandinc/vscode-appland/issues/316.
=> fix: Do not show instructions popup automatically

package.json, src/contextMenu.ts, src/extension.ts, src/tree/appmap/AppMapTreeDataProvider.ts
Fixes #304 
Fixes #305
Fixes #306
=> feat: add context menu to appmap panel

src/appmapUploader.ts, src/extension.ts, src/remoteRecordingClient.ts, src/scenarioViewer.ts, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, web/src/appmapView.js
Implemented telemetry events:
- appmap:upload
- remote_recording:start
- remote_recording:stop
- remote_recording:status
- telemetry
Fixes #314 
Fixes #313 
Fixes #266  
Fixes #211
Fixes #212 
Fixes #213 
Fixes #214 
Fixes #215 
Fixes #216
=> Telemetry events

package.json, src/agent/AppMapAgentDummy.ts, src/agent/appMapAgentRuby.ts, src/extension.ts, src/quickstart-docs/installAgentWebview.ts, src/quickstart-docs/openAppmapsWebview.ts, src/quickstart-docs/recordAppmapsWebview.ts, src/quickstart-docs/welcomeWebview.ts, src/telemetry/definitions/events.ts, src/telemetry/event.ts, src/tree/quickstartDocsTreeDataProvider.ts, test/mocks/mockFileSystemWatcher.ts, test/specs/quickstart.test.ts, web/src/app.js, web/src/quickstartDocsView.js, yarn.lock
Fixes #300 
Fixes #312
Fixes #330
Fixes https://github.com/applandinc/appmap-js/issues/291
=> Docs based flow

README.md
This PR Updates the ReadMe to include the installer command and system requirements. It is common for users to visit this page after installing the extension. This goal is to increase the number of users with appropriate projects running the installer.
=> docs: README includes the installer command and sys requirements

src/remoteRecording.ts
=> feat: show progress notification when remote recording is running

package.json, src/agent/appMapAgentRuby.ts, src/analyzers/javascript.ts, src/languageResolver.ts, yarn.lock
=> feat: JavaScript support in the project picker

README.md
This change includes some whitespace edits as well. I've split the commits into two: one for content changes (1aec236ec64c9ed6bf748ecedd5406ed86ee42ef) and another for formatting.
**Please squash merge me otherwise I won't deploy!**
=> fix: Document availability of AppMap for JavaScript

package.json, web/src/appmapView.js, yarn.lock
Fixes: https://linear.app/appland/issue/MAP-302/update-view-source-buttons-in-vscode-appland
=> Update `@appland/components` dependency

src/commands/deleteAllAppMaps.ts, src/services/appmapUptodateService.ts, src/tree/classMapTreeDataProvider.ts, src/util.ts, test/fixtures/workspaces/project-a/package.json, yarn.lock
A couple of issues that I hit doing testing.
=> fix: Misc service errors

package.json
Arguments passed to commands in `package.json` need to be URI-encoded strings
Resolves MAP-375
=> fix: update blue welcome button in sidebar

README.md, package.json, src/agent/AppMapAgentDummy.ts, src/agent/appMapAgent.ts, src/agent/appMapAgentRuby.ts, src/analyzers/index.ts, src/analyzers/python.disabled.ts, src/configuration/extensionSettings.ts, src/services/languageResolver.ts, src/webviews/installGuideWebview.ts, src/webviews/projectPickerWebview.ts, test/system/tests/instructions.test.ts, test/system/tests/support/project.ts
Also, add a fix that seems to have improved the test hit rate (maybe in combination with e4bcbfe). It's still not 100%, though. https://app.travis-ci.com/github/applandinc/vscode-appland/builds/252158020 failed, even though several builds before it were green. When rerun, it passed: https://app.travis-ci.com/github/applandinc/vscode-appland/builds/252158427 .
Fixes https://github.com/applandinc/board/issues/30 .
=> Feature flag python support

package.json, src/webviews/projectPickerWebview.ts, test/system/tests/instructions.test.ts, yarn.lock
Updated version of `@appland/components` in `package.json`
=> Fix: update components version

package.json, src/configuration/extensionSettings.ts, src/editor/appmapEditorProvider.ts
@apotterri for your review and enjoyment:
https://www.loom.com/share/a0035c6ee67543dab6aada7b4b49b335
=> feat: Default view configuration setting

src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, src/webviews/installGuideWebview.ts, web/src/installGuideView.js
=> feat: add telemetry info from project picker

src/commands/installAgent.ts, test/integration/command/installAgent.test.ts
=> Properly escape paths during installation

package.json, src/lib/ValueCache.ts, src/lib/firstLine.ts, src/lib/generateDisplayTitle.ts, src/lib/memoize.ts, src/lib/present.ts, src/lib/uniq.ts, src/services/resolvedFinding.ts, src/tree/findingsTreeDataProvider.ts, yarn.lock
(Note https://github.com/getappmap/appmap-js/pull/788 is needed to fix the build.)
Before:
After:
Fixes #478 
I also noticed another problem while working on this: #479
=> Improve formatting of findings tree view

src/services/findingsIndex.ts, src/services/projectStateService.ts, test/integration/findingsImpactDomains/severalFindings.test.ts
=> fix: Finding counts in the instructions view is consistent

src/actions/signup.ts, src/authentication/appmapServerAuthenticationProvider.ts, src/services/analysisManager.ts, src/services/processWatcher.ts, src/telemetry/definitions/events.ts, src/telemetry/index.ts, test/integration/nodeProcesses/backgroundProcess.test.ts
Best reviewed commit by commit
=> Notify on analysis and authentication state changes

src/commands/installAgent.ts, test/integration/command/installAgent.test.ts
Addresses https://github.com/getappmap/board/issues/196
=> fix: Add @latest tag in install prompt.

appmap.yml, src/authentication/appmapServerAuthenticationProvider.ts
While authenticating the user, send their machine id
Companion PR - https://github.com/getappmap/appmap-server/pull/1200
=> feat: Submit azure user id on login

package.json, src/services/nodeDependencyProcess.ts, yarn.lock
Support Scanner with `appMap.commandLineToolsPath`
=> dev: Local AppMap services

package.json, src/editor/AppMapDocument.ts, src/editor/appmapEditorProvider.ts, src/lib/getStackLocations.ts, src/tree/findingsTreeDataProvider.ts, src/webviews/findingInfoWebview.ts, yarn.lock
Fixes #568
Should be reviewed and merged AFTER [this PR](https://github.com/getappmap/appmap-js/pull/887).
This attaches relevant findings information to appmaps when they are processed for viewing using our custom editor in VS Code.
=> Findings info in appmap

package.json, src/actions/appmapUploader.ts, src/editor/appmapEditorProvider.ts, web/src/appmapView.js, yarn.lock
Fixes #575 
These changes support frontend webview changes that update and improve the share button in the map view.
=> Update VS Code to support share button updates

DEVELOPMENT.md, README.md, package.json, yarn.lock
=> Add terms of service to readme

package.json, src/configuration/extensionSettings.ts, src/editor/appmapEditorProvider.ts, web/src/appmapView.js
Fixes #604 
Puts the Share button behind a feature flag that can be toggled by a user.
=> Share button behind feature flag

package.json, yarn.lock
Minor text update for the Analysis CTA in the sidebar to put user's minds at ease about their data privacy.
New:
Old:
=> Sign Up CTA text update

package.json, src/extension.ts, src/services/signInManager.ts, src/telemetry/definitions/errorCodes.ts, src/telemetry/definitions/events.ts, src/webviews/signInWebview.ts, web/src/app.js, web/src/signInView.js
=> Require sign-in for new users

package.json, src/extension.ts, src/services/signInManager.ts, src/telemetry/definitions/errorCodes.ts, src/telemetry/definitions/events.ts, src/webviews/signInWebview.ts, web/src/app.js, web/src/signInView.js, yarn.lock
See https://github.com/getappmap/vscode-appland/pull/627
=> Require sign in for new users

src/extension.ts, src/services/signInManager.ts, src/webviews/installGuideWebview.ts
=> fix: do not let users bypass sign-in

.github/workflows/test.yml, package.json, src/lib/git.ts, src/services/projectStateService.ts, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, src/telemetry/telemetryDataProvider.ts, test/integration/authentication/appmapServerLogin.test.ts, test/unit/lib/git.test.ts, test/unit/mock/vscode/EventEmitter.ts, test/unit/mock/vscode/extensions.ts, test/unit/mock/vscode/index.ts, test/unit/services/nodeDependencyProcess.test.ts, test/unit/services/processWatcher.test.ts, types/vscode.git.d.ts, yarn.lock
=> Add project root and repository to project:open telemetry

src/commands/tryOpenInstallGuide.ts, src/extension.ts, src/services/signInManager.ts, src/tree/classMapTreeDataProvider.ts, src/webviews/installGuideWebview.ts, test/disabled/installGuide.test.ts, test/integration/authentication/sidebarSignIn.test.ts
=> Add tests for new sign in flow

package.json, src/configuration/extensionState.ts, src/editor/appmapEditorProvider.ts, src/telemetry/definitions/errorCodes.ts, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, web/src/appmapView.js, yarn.lock
Fixes #644 
This update is the companion change to [this PR](https://github.com/getappmap/appmap-js/pull/1086). 
* A VS Code notification will pop up after a user views a sequence diagram for one minute continuously (the timer will reset if the appmap tab is changed or if the VS Code tab is changed). The notification will only appear once.
Here is a VSIX if you want to test it:
[appmap-0.69.3.zip](https://github.com/getappmap/vscode-appland/files/10913238/appmap-0.69.3.zip)
To get the notification to appear again, open the control palette (`Ctrl + Shift + P`), then run the command `AppMap: Reset Usage State`, then reload the window, and then the notification will show up again after one minute on a sequence diagram.
=> Prompt user for feedback about sequence diagrams

src/editor/appmapEditorProvider.ts, test/disabled/installGuide.test.ts, test/systemTest.ts
Needed to release the handling of large appmaps.
=> Release handling of large appmaps

package.json, src/analyzers/javascript.ts, test/unit/analyzers/javascript.test.ts, test/unit/mock/vscode/index.ts, test/unit/mock/vscode/uri.ts, test/unit/mock/vscode/workspace.ts
=> Jest support in the project picker

package.json, src/commands/compareSequenceDiagram.ts, src/commands/findByName.ts, src/commands/generateOpenApi.ts, src/commands/openCodeObjectInAppMap.ts, src/commands/resetUsageState.ts, src/commands/sequenceDiagram.ts, src/extension.ts, src/lib/AppMapQuickPickItem.ts, src/lib/deleteAppMap.ts, src/lib/promptForAppMap.ts, src/lib/sequenceDiagram.ts, src/services/appmapCollection.ts, src/services/appmapCollectionFile.ts, src/services/appmapFinder.ts, src/util.ts, test/integration/sequenceDiagram/compareSequenceDiagrams.test.ts, test/integration/sequenceDiagram/sequenceDiagram.test.ts
Use the enhanced quick-pick to select an AppMap.
Feature commits:
* [feat: Open Code Object in AppMap uses enhanced prompt](https://github.com/getappmap/vscode-appland/pull/676/commits/b21deb406bc72ee018bc6c81a6bbcea676f9bddc)
* [feat: Open AppMap by Name uses enhanced prompt](https://github.com/getappmap/vscode-appland/pull/676/commits/48f5850eb0e3c0e03a0c570f3311f1fd9421cff0)
=> feat: Quick pick appmap

src/tree/links.ts, test/unit/tree/links.test.ts
Also, add a comment to remind about updating IntelliJ.
=> test: Verify that documentation links are valid

package.json, src/configuration/extensionSettings.ts, src/editor/appmapEditorProvider.ts, web/src/appmapView.js, yarn.lock
This flag is consumed by the peer PR: https://github.com/getappmap/appmap-js/pull/1192
=> feat: add flame graph setting

package.json, src/configuration/extensionSettings.ts, src/editor/appmapEditorProvider.ts, web/src/appmapView.js, yarn.lock
Reverts flamegraph because we're having problems with the zoom and pan functionality in the Dependency Map and the Trace View.
=> Revert flamegraph

package.json, src/editor/appmapEditorProvider.ts, src/extension.ts, src/lib/initializeSavedFilters.ts, test/integration/index/updateAsAppMapsAreModified.test.ts, test/integration/savedFilters.test.ts, test/integration/scanner/performAsAppMapsAreModified.test.ts, web/src/appmapView.js, yarn.lock
Fixes #681 
This incorporates the frontend changes from [this PR](https://github.com/getappmap/appmap-js/pull/1186) and adds logic to store and update saved filters.
=> User can configure default appmap filter settings

package.json, src/configuration/extensionState.ts, src/extension.ts, src/lib/deleteAppMap.ts, src/lib/indexJanitor.ts, src/services/appmapCollection.ts, src/services/appmapCollectionFile.ts, src/services/projectStateService.ts, test/integration/lib/indexJanitor.test.ts, test/system/src/instructionsWebview.ts, test/system/tests/instructions.test.ts, yarn.lock
[Peek 2023-06-08 16-56.webm](https://github.com/getappmap/vscode-appland/assets/8737782/bf029927-d349-4b1c-b0d5-8f43119123bf)
Fixes #550
=> Presence of AppMaps is now more accurately presented in the sidebar

src/editor/appmapEditorProvider.ts, test/integration/savedFilters.test.ts
Fixes #727 
Fixes a bug where users could not update an existing saved filter.
=> Users can update an existing filter

src/commands/installer/default.ts, src/commands/installer/python.ts, src/commands/installer/terminals.ts, src/extension.ts, src/lib/dictEqual.ts, test/integration/command/installAgent.test.ts, test/integration/command/installer/python.test.ts, test/unit/lib/dictEqual.test.ts
=> feat: Reuse existing terminals when rerunning installer if possible

src/lib/githubRelease.ts, src/services/assetManager.ts, test/integration/assetManager/javaJarDownload.test.ts, test/integration/assetManager/javaJarLockfileExists.test.ts
=> Update error reporting for java jar download

package.json
=> Remove sidebar panes when signed out

package.json, yarn.lock
Fixes #749 
Update flame graph to the latest version with all of the tweaks.
=> Update flame graph

src/lib/deleteAppMap.ts, src/services/appmapConfigManager.ts, src/webviews/installGuideWebview.ts, src/workspace/projectMetadata.ts, test/integration/analysisTree/enumerateTree.ts, test/integration/analysisTree/failedTest.test.ts, test/integration/analysisTree/recentFinding.test.ts, test/integration/analysisTree/removeFindingModifiedDate.ts, test/integration/analysisTree/treeItems.test.ts, test/integration/appmapConfigManager/appmapConfigManager.test.ts, test/integration/runConfigs/runConfigsJava.test.ts, test/integration/runConfigs/runConfigsJavaNoTestExt.test.ts, test/integration/runConfigs/runConfigsRuby.test.ts, test/integration/runConfigs/testConfigsJava.test.ts, test/unit/services/processWatcher.test.ts, test/waitFor.ts
=> Fix linter warnings

src/commands/compareSequenceDiagram.ts, src/commands/findByName.ts, src/commands/openCodeObjectInAppMap.ts, src/commands/openFinding.ts, src/commands/sequenceDiagram.ts, src/extension.ts, src/lib/promptForAppMap.ts, src/lib/saveAppMapToCollection.ts, src/services/analysisManager.ts, src/tree/contextMenu.ts, src/util.ts
@dustinbyrne FYI let's see how this goes...
=> refactor: Simplify getWorkspaceFolderFromPath

package.json, src/configuration/extensionSettings.ts, src/editor/appmapEditorProvider.ts, web/src/appmapView.js, yarn.lock
Fixes #753 
Merging this PR will "release" flame graph.
=> Remove flame graph feature flag

package.json, yarn.lock
=> Update dependencies to release improved findings hightlighting

package.json, src/services/projectStateService.ts, yarn.lock
When the agent and run configurations exist, the Java installation will be flagged as complete.
=> feat: Update the Java installation condition

README.md
Also added a link to our security / data handling policy
=> Making JS mentions Node-specific

package.json, yarn.lock
=> Update @appland/components to 2.58.0

package.json, src/commands/generateOpenApi.ts, src/configuration/extensionState.ts, src/extension.ts, src/services/projectStateService.ts, src/tree/instructionsTreeDataProvider.ts, src/webviews/installGuideWebview.ts, src/workspace/projectMetadata.ts, test/system/src/appMap.ts, test/system/tests/instructions.test.ts, web/src/installGuideView.js, yarn.lock
=> Drop OpenAPI from the onboarding flow

.vscode/launch.json, package.json, src/editor/AppMapDocument.ts, src/editor/appmapEditorProvider.ts, src/services/appmapServerConfiguration.ts, test/fixtures/workspaces/project-diagram-diff/data/diff/minitest/Users_edit_unsuccessful_edit.diff.sequence.json, test/fixtures/workspaces/project-diagram-diff/data/head/minitest/Users_edit_unsuccessful_edit.appmap.json, test/integration/editor/openSequenceDiagramDiff.test.ts, test/integration/util.ts, web/src/appmapView.js, yarn.lock
File association for '*.diff.sequence.json'.
Related: https://github.com/getappmap/appmap-js/pull/1339
=> feat: Display *.diff.sequence.json files

package.json, yarn.lock
=> feat: Upgrade @appland/components to v2.62.0

src/actions/promptInstall.ts, test/integration/actions/promptInstall.test.ts
=> Prompt Java and Python to install AppMap

src/configuration/extensionState.ts, src/extension.ts, src/lib/firstAppMapNotification.ts, src/tree/appMapTreeDataProvider.ts, src/tree/index.ts, src/webviews/installGuideWebview.ts, test/integration/lib/firstAppMapNotification.test.ts
=> feat: New users see a notification box when they create their first map

src/services/javaAssets.ts, src/webviews/installGuideWebview.ts, test/unit/lib/javaAssets.test.ts
=> fix: Instructions page should be reactive to the Java agent file

src/lib/buildClassMap.ts, src/tree/classMapTreeDataProvider.ts, test/fixtures/workspaces/project-external-service/tmp/appmap/external_service_example.appmap.json, test/integration/classMapTree/externalService.test.ts
Fixes https://github.com/getappmap/appmap-js/issues/1267.
=> feat: The Code Objects view also lists External Service Calls

package.json, yarn.lock
=> Update @appland/components to 3.8.0

src/configuration/extensionState.ts, src/services/projectStateService.ts, src/webviews/installGuideWebview.ts, test/integration/findingsImpactDomains/severalFindings.test.ts, test/system/tests/instructions.test.ts
Fixes: [#1403](https://github.com/getappmap/appmap-js/issues/1403)
feat(projectStateService.ts): enhance hasInvestigatedFindings check
test(instructions.test.ts): add test for runtime analysis status transitions
=> Runtime Analysis is determined complete on multiple checks.

package.json, yarn.lock
=> Update @appland/components to 3.9.0

src/editor/appmapEditorProvider.ts
=> Fix source links with drive letters on Windows

package.json, src/configuration/extensionSettings.ts, src/services/indexProcessWatcher.ts, src/services/scanProcessWatcher.ts, yarn.lock
Add 'appmap index' options via appMap.appMap.indexOptions setting Add '--verbose' flag to 'index' and 'scan' via appmap.commandLineVerbose
=> feat: Configurable CLI flags

package.json
=> feat: Rename "AppMap AI: Explain" to "AppMap: Ask Navie AI"

package.json, src/webviews/chatSearchWebview.ts, web/src/chatSearchView.js, yarn.lock
Pre-requisite: https://github.com/getappmap/appmap-js/pull/1576
=> Handle open-record-instructions from navie instructions

.travis.yml, package.json, src/commands/quickSearch.ts, src/configuration/extensionSettings.ts, src/services/processWatcher.ts, src/webviews/chatSearchWebview.ts, src/webviews/getWebviewContent.ts, test/systemTest.ts, test/unit/commands/quickSearch.test.ts, test/unit/mock/vscode/TextDocument.ts, web/src/chatSearchView.js, yarn.lock
This change integrates the frontend code selection component.
https://github.com/getappmap/vscode-appland/assets/8737782/60195cc7-4453-420d-a5a2-6942c23ad7ff
https://github.com/getappmap/vscode-appland/pull/878/commits/a0a5e91f8db581bc749b34ff9aa0d8a7932b1cd6 and https://github.com/getappmap/vscode-appland/pull/878/commits/f537c19fc0bfa7959e182042b143a021cd0766b8 were previously approved/merged via https://github.com/getappmap/vscode-appland/pull/855 but appear to have been dropped during a rebase at some point.
=> feat: Integrate the code snippet frontend

src/commands/quickSearch.ts, test/unit/commands/quickSearch.test.ts
"Explain with AppMap AI" -> "Explain with AppMap Navie AI"
=> feat: Rename Navie code action

package.json
=> fix: Update Navie AI command name

package.json, src/tree/index.ts, src/webviews/chatSearchWebview.ts, web/src/chatSearchView.js, yarn.lock
- Updates Navie styling (see [here](https://github.com/getappmap/appmap-js/pull/1589))
- Handles event from clicking `Looking for code visualizations?` by opening the AppMaps tree (see picture).
=> Update Navie chat interface

README.md
You the vimeo embed code for the Navie video as well as updating the other video moving from YT to vimeo
This PR needs to be merged first: https://github.com/getappmap/applandinc.github.io/pull/1245
=> Add Vimeo video embed

src/authentication/appmapServerAuthenticationProvider.ts
=> Entering license manually closes sign in panel

src/commands/quickSearch.ts
There's no reason not to offer Navie in those languages.
=> feat: Add Navie explain code action provider to jsx and tsx

package.json, src/commands/commandRegistry.ts, src/commands/quickSearch.ts, src/editor/appmapEditorProvider.ts, src/webviews/chatSearchWebview.ts, web/src/appmapView.js, web/src/chatSearchView.js, yarn.lock
Releases the feature where a user can open Navie from within an AppMap and ask about it.
=> Release open Navie from an appmap

src/services/languageResolver.ts
This adds `.tsx` files for JavaScript projects.
=> Include .tsx files for node projects

README.md
Updates the README to highlight and explain Navie.
=> Update README to feature Navie

package.json, src/util.ts, src/webviews/chatSearchWebview.ts, test/unit/mock/vscode/Location.ts, test/unit/mock/vscode/index.ts, test/unit/mock/vscode/workspace.ts, test/unit/util.test.ts, web/src/chatSearchView.js, yarn.lock
=> feat: Integrate the context pane

package.json
OLD: Runtime diagrams + Navie AI Software Architect
NEW: Free AI Software Architect + Runtime Diagrams
=> Update marketplace description to include 'Free'

package.json
[Update description](https://github.com/getappmap/vscode-appland/commit/b70f3b039a3b145f598e27c738cfbca4a9a16d9f)
Change Navie command name to "AppMap: Ask Navie AI"
=> Marketplace release

resources/versions.json, src/lib/proxySettings.ts, src/telemetry/definitions/events.ts, src/telemetry/definitions/properties.ts, src/webviews/chatSearchWebview.ts, test/unit/proxySettings.test.ts
Report presence of proxy settings to `project:open` telemetry.
=> feat: Report proxy settings

package.json, src/webviews/chatSearchWebview.ts, test/integration/chat/chat.test.ts, web/src/chatSearchView.js, yarn.lock
Fix hang in the chat integration tests.
Test for this will fail until https://github.com/getappmap/appmap-js/pull/1990 is merged.
Fixes #1019
=> Wait till ChatSearch fully initializes

package.json, src/configuration/extensionSettings.ts, src/webviews/chatSearchWebview.ts, web/src/app.js, web/src/chatSearchView.js, web/static/styles/navie-integration.css, yarn.lock
Use the latest version of `@appland/components` to show improved pinning help. Also, add setting to turn off animation in the Chat UI, and fix a problem that keeps the Chat input from getting focus.
Needs https://github.com/getappmap/appmap-js/pull/2005 merged.
=> Show pinning help

package.json, src/authentication/appmapServerAuthenticationProvider.ts, src/authentication/authenticationStrategy/index.ts, src/authentication/authenticationStrategy/localWebServer.ts, src/authentication/authenticationStrategy/vscodeProtocolRedirect.ts, src/authentication/index.ts, src/extension.ts, src/services/signInManager.ts, src/webviews/signInWebview.ts, test/integration/authentication/appmapServerLogin.test.ts, test/unit/authentication/authenticationStrategy/vscodeProtocolRedirect.test.ts, web/src/signInView.js, yarn.lock
When logging in with GitHub or GitLab, go straight to the appropriate
target site, instead of landing on getappmap.com/login.
This is the final piece of work for https://github.com/getappmap/board/issues/338 .
=> Skip login page when authenticating with SSO

src/configuration/extensionState.ts, src/services/signInManager.ts, test/unit/sidebarSignIn.test.ts
And it opens to the correct page (the Navie walkthrough)
=> fix: The walkthrough now only opens once

package.json
`AI`, `Chat` are new and more relevant.
=> fix: Change categories

src/services/chatCompletion.ts
This change handles `Error: Response got filtered.`, propagating it to the OpenAI API client via the `content_filter` finish reason. This allows the client to notify the client that their response was terminated.
=> fix: Propagate Copilot content filter errors

package.json, src/extension.ts, src/services/chatCompletion.ts, src/services/navieConfigurationService.ts, src/services/processWatcher.ts, src/services/rpcProcessService.ts, src/services/rpcProcessWatcher.ts, src/webviews/chatSearchWebview.ts, test/unit/services/chatCompletion.test.ts, test/unit/services/navieConfigurationService.test.ts, test/unit/services/processWatcher.test.ts, test/unit/services/rpcProcessService.test.ts, web/src/chatSearchView.js, yarn.lock
This pull request introduces a new model selection and configuration interface for Navie AI, replacing the previous mechanism for choosing between the default AppMap backend, Copilot, or a user-provided OpenAI key.
Key Changes:
Model Selection UI: Integrates a new UI component within the Navie chat view that allows users to browse available AI models (including detected Copilot models) and select one for use.
Configuration Setting: Introduces a new VS Code setting, appMap.selectedModel, to store the identifier of the user's chosen model.
Centralized Secret Management: Refactors the handling of sensitive information like API keys.
Moves away from the dedicated openai.api_key secret.
Introduces a new structured secret, appmap.navie.env, stored in VS Code's secret storage to hold environment …
=> feat: Integrate the model selector

README.md
This change brings the product description in line with the marketing on https://appmap.io
=> fix: Update marketplace description

test/integration/classMap/service.test.ts, test/waitFor.ts, yarn.lock
=> Fix and reenable flaky test
